# Generated by Django 4.0.4 on 2022-05-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='owner',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
