# Generated by Django 4.0.4 on 2022-06-29 01:10

import auctions.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_auctionitem_highest_bidder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='image',
            field=models.ImageField(upload_to=auctions.models.AuctionItem.user_directory_path),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='watching',
            field=models.ManyToManyField(blank=True, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
