# Generated by Django 4.0.4 on 2022-06-29 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_auctionitem_image_alter_auctionitem_watching'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='image',
            field=models.ImageField(upload_to='{self.title}/{self.owner}'),
        ),
    ]
