# Generated by Django 4.0.4 on 2022-06-29 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_auctionitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='image',
            field=models.ImageField(upload_to='<django.db.models.fields.CharField>/<django.db.models.fields.related.ForeignKey>'),
        ),
    ]
