# Generated by Django 4.0.4 on 2022-06-29 03:51

import auctions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_auctionitem_highest_bidder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=auctions.models.AuctionItem.user_directory_path),
        ),
    ]
