# Generated by Django 4.0.4 on 2022-10-12 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_remove_relationship_following_relationship_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Relationship',
        ),
    ]
